# Generated by Django 6.0.5 on 2026-06-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtemplate',
            name='icon',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
