# Generated by Django 6.0.5 on 2026-06-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_subscriptionplan_user_type'),
        ('admin_api', '0005_alter_cardtemplate_icon_and_more'),
    ]

    operations = [
    ]
