# Generated by Django 6.0.5 on 2026-07-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_change_billing_to_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
