# Generated by Django 6.0.5 on 2026-07-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0008_subscriptionplan_discount_subscriptionplan_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='orginal_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
